name: hpc-example
channels: 
        - defaults
        - conda-forge
dependencies:
        - pytorch
        - pytorch-lightning
        - torchvision
        - torchmetrics
        - setuptools==59.5.0
        - lightning-bolts
        - jsonargparse
